services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "32MB"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pit_dev
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "160MB"

  app1:
    build:
      context: .
    container_name: app1
    environment:
      MIX_ENV: dev
    expose:
      - "4000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "79MB"

  app2:
    build:
      context: .
    container_name: app2
    environment:
      MIX_ENV: dev
    expose:
      - "4000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "79MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  db:
    driver: local
