version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"
  app1:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SECRET_KEY_BASE=Iy1WZcjmLJcfomKxtskVeAsmyek9/SM8E4DMZp2wjd70fN1vHhi4W9zE1gSDC9Kh
      - PORT=9999
      - PHX_SERVER=true
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "130MB"
    restart: unless-stopped
  app2:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SECRET_KEY_BASE=Iy1WZcjmLJcfomKxtskVeAsmyek9/SM8E4DMZp2wjd70fN1vHhi4W9zE1gSDC9Kh
      - PORT=9999
      - PHX_SERVER=true
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "130MB"
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
