services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pit_dev
    volumes:
      - db:/var/lib/postgresql/data

  app1:
    build:
      context: .
    container_name: app1
    environment:
      MIX_ENV: dev
    # ports:
    #   - "4000:4000"
    expose:
      - "4000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend
      - payment-processor

  app2:
    build:
      context: .
    container_name: app2
    environment:
      MIX_ENV: dev
    # ports:
    #   - "4000:4000"
    expose:
      - "4000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend
      - payment-processor

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  db:
    driver: local
